services:
  # Configurazione del container per PHP
  app:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  # Configurazione del container per MySQL
  db:
    image: mysql:8
    container_name: dreamcity-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dreamcity_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
